# Generated by Django 5.2.1 on 2025-05-31 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_usuario_groups_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario',
            new_name='username',
        ),
    ]
